// src/data/biologyData.js
// ============================================
// Biology Chapters Data organized by Grade and Board

export const biologyChaptersData = {
  "Grade 6": {
    CBSE: [
      {
        id: 1,
        title: "Food: Where Does it Come From?",
        description: "Sources of food",
        difficulty: "Beginner",
        duration: "30 min",
        topics: 3,
        progress: 0,
      },
      {
        id: 2,
        title: "Components of Food",
        description: "Nutrients in food",
        difficulty: "Beginner",
        duration: "35 min",
        topics: 4,
        progress: 0,
      },
      {
        id: 3,
        title: "Body Movements",
        description: "Skeleton and muscles",
        difficulty: "Beginner",
        duration: "38 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 4,
        title: "Living and Non-living",
        description: "Characteristics of life",
        difficulty: "Beginner",
        duration: "32 min",
        topics: 3,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "The Leaf",
        description: "Structure and function",
        difficulty: "Beginner",
        duration: "35 min",
        topics: 4,
        progress: 0,
      },
      {
        id: 2,
        title: "The Cell",
        description: "Basic unit of life",
        difficulty: "Beginner",
        duration: "38 min",
        topics: 4,
        progress: 0,
      },
    ],
    WBSE: [
      {
        id: 1,
        title: "Living World",
        description: "Classification basics",
        difficulty: "Beginner",
        duration: "35 min",
        topics: 4,
        progress: 0,
      },
    ],
  },

  "Grade 7": {
    CBSE: [
      {
        id: 1,
        title: "Nutrition in Plants",
        description: "Photosynthesis",
        difficulty: "Intermediate",
        duration: "42 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 2,
        title: "Nutrition in Animals",
        description: "Digestive system",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 3,
        title: "Respiration in Organisms",
        description: "Breathing and cellular respiration",
        difficulty: "Intermediate",
        duration: "42 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 4,
        title: "Transportation in Plants and Animals",
        description: "Circulatory system",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Plant and Animal Tissues",
        description: "Types of tissues",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 2,
        title: "Photosynthesis",
        description: "Process and importance",
        difficulty: "Intermediate",
        duration: "42 min",
        topics: 5,
        progress: 0,
      },
    ],
    WBSE: [
      {
        id: 1,
        title: "Life Processes",
        description: "Nutrition and respiration",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 6,
        progress: 0,
      },
    ],
  },

  "Grade 8": {
    CBSE: [
      {
        id: 1,
        title: "Crop Production and Management",
        description: "Agricultural practices",
        difficulty: "Beginner",
        duration: "35 min",
        topics: 4,
        progress: 0,
      },
      {
        id: 2,
        title: "Microorganisms",
        description: "Friend and foe",
        difficulty: "Intermediate",
        duration: "42 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 3,
        title: "Reproduction in Animals",
        description: "Sexual and asexual reproduction",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 4,
        title: "Reaching the Age of Adolescence",
        description: "Puberty and hormones",
        difficulty: "Intermediate",
        duration: "40 min",
        topics: 5,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Cell Structure and Functions",
        description: "Organelles",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Reproduction",
        description: "Types and processes",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
    ],
    WBSE: [
      {
        id: 1,
        title: "Cell and Tissues",
        description: "Structure and function",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 6,
        progress: 0,
      },
    ],
  },

  "Grade 9": {
    CBSE: [
      {
        id: 1,
        title: "The Fundamental Unit of Life",
        description: "Cell structure, organelles and functions",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Tissues",
        description: "Plant and animal tissues",
        difficulty: "Intermediate",
        duration: "50 min",
        topics: 7,
        progress: 0,
      },
      {
        id: 3,
        title: "Diversity in Living Organisms",
        description: "Classification and taxonomy",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 9,
        progress: 0,
      },
      {
        id: 4,
        title: "Why Do We Fall Ill",
        description: "Health and diseases",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 5,
        title: "Natural Resources",
        description: "Conservation and sustainability",
        difficulty: "Intermediate",
        duration: "42 min",
        topics: 5,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "The Cell",
        description: "Cell theory and structure",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Tissues",
        description: "Animal and plant tissues",
        difficulty: "Intermediate",
        duration: "50 min",
        topics: 7,
        progress: 0,
      },
      {
        id: 3,
        title: "The Flower",
        description: "Structure and reproduction",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 4,
        title: "Classification of Plants",
        description: "Plant kingdom",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 8,
        progress: 0,
      },
    ],
    WBSE: [
      {
        id: 1,
        title: "Cell Biology",
        description: "Structure and organelles",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Living World Classification",
        description: "Kingdoms and phyla",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 3,
        title: "Life Processes",
        description: "Nutrition and transport",
        difficulty: "Intermediate",
        duration: "50 min",
        topics: 7,
        progress: 0,
      },
    ],
    "State Board": [
      {
        id: 1,
        title: "Cell - Basic Unit of Life",
        description: "Cell structure",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Tissues",
        description: "Types and functions",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
    ],
  },

  "Grade 10": {
    CBSE: [
      {
        id: 1,
        title: "Life Processes",
        description: "Nutrition, respiration, transport and excretion",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 9,
        progress: 0,
      },
      {
        id: 2,
        title: "Control and Coordination",
        description: "Nervous and hormonal systems",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 3,
        title: "How Do Organisms Reproduce?",
        description: "Reproduction in plants and animals",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 4,
        title: "Heredity and Evolution",
        description: "Genetics, DNA and natural selection",
        difficulty: "Advanced",
        duration: "62 min",
        topics: 10,
        progress: 0,
      },
      {
        id: 5,
        title: "Our Environment",
        description: "Ecosystem and food chains",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Cell Division",
        description: "Mitosis and meiosis",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 7,
        progress: 0,
      },
      {
        id: 2,
        title: "Genetics",
        description: "Mendelian inheritance",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 9,
        progress: 0,
      },
      {
        id: 3,
        title: "The Nervous System",
        description: "Structure and function",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 4,
        title: "The Circulatory System",
        description: "Heart and blood vessels",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 7,
        progress: 0,
      },
    ],
    WBSE: [
      {
        id: 1,
        title: "Life Processes and Control",
        description: "Coordination in living beings",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 2,
        title: "Reproduction and Heredity",
        description: "Genetics basics",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 9,
        progress: 0,
      },
      {
        id: 3,
        title: "Environment and Ecology",
        description: "Ecosystem dynamics",
        difficulty: "Intermediate",
        duration: "50 min",
        topics: 7,
        progress: 0,
      },
    ],
    "State Board": [
      {
        id: 1,
        title: "Life Processes",
        description: "Essential functions",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 2,
        title: "Heredity",
        description: "Genetics",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 9,
        progress: 0,
      },
    ],
  },

  "Grade 11": {
    CBSE: [
      {
        id: 1,
        title: "The Living World",
        description: "What is living",
        difficulty: "Beginner",
        duration: "40 min",
        topics: 4,
        progress: 0,
      },
      {
        id: 2,
        title: "Biological Classification",
        description: "Five kingdom classification",
        difficulty: "Intermediate",
        duration: "55 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 3,
        title: "Plant Kingdom",
        description: "Classification of plants",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 9,
        progress: 0,
      },
      {
        id: 4,
        title: "Animal Kingdom",
        description: "Classification of animals",
        difficulty: "Advanced",
        duration: "62 min",
        topics: 10,
        progress: 0,
      },
      {
        id: 5,
        title: "Cell - The Unit of Life",
        description: "Cell structure and function",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 8,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Biomolecules",
        description: "Proteins, carbohydrates, lipids",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 9,
        progress: 0,
      },
      {
        id: 2,
        title: "Cell Biology",
        description: "Cell organelles",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 8,
        progress: 0,
      },
    ],
  },

  "Grade 12": {
    CBSE: [
      {
        id: 1,
        title: "Reproduction in Organisms",
        description: "Modes of reproduction",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 7,
        progress: 0,
      },
      {
        id: 2,
        title: "Sexual Reproduction in Flowering Plants",
        description: "Pollination and fertilization",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 9,
        progress: 0,
      },
      {
        id: 3,
        title: "Human Reproduction",
        description: "Reproductive system",
        difficulty: "Advanced",
        duration: "62 min",
        topics: 10,
        progress: 0,
      },
      {
        id: 4,
        title: "Principles of Inheritance",
        description: "Mendelian genetics",
        difficulty: "Advanced",
        duration: "65 min",
        topics: 11,
        progress: 0,
      },
      {
        id: 5,
        title: "Molecular Basis of Inheritance",
        description: "DNA and RNA",
        difficulty: "Advanced",
        duration: "68 min",
        topics: 12,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Genetics",
        description: "Advanced genetics",
        difficulty: "Advanced",
        duration: "65 min",
        topics: 11,
        progress: 0,
      },
      {
        id: 2,
        title: "Evolution",
        description: "Theories and evidence",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 9,
        progress: 0,
      },
    ],
  },
};