// src/data/physicsData.js
// ============================================
// Physics Chapters Data organized by Grade and Board

export const physicsChaptersData = {
  "Grade 6": {
    CBSE: [
      {
        id: 1,
        title: "Light, Shadows and Reflections",
        description: "Understanding light and its properties",
        difficulty: "Beginner",
        duration: "35 min",
        topics: 4,
        progress: 0,
      },
      {
        id: 2,
        title: "Electricity and Circuits",
        description: "Basic electrical circuits",
        difficulty: "Beginner",
        duration: "40 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 3,
        title: "Fun with Magnets",
        description: "Properties of magnets",
        difficulty: "Beginner",
        duration: "30 min",
        topics: 3,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Matter and Materials",
        description: "Properties of matter",
        difficulty: "Beginner",
        duration: "38 min",
        topics: 4,
        progress: 0,
      },
      {
        id: 2,
        title: "Force and Energy",
        description: "Understanding force",
        difficulty: "Beginner",
        duration: "42 min",
        topics: 5,
        progress: 0,
      },
    ],
    WBSE: [
      {
        id: 1,
        title: "Physical World",
        description: "Introduction to physics",
        difficulty: "Beginner",
        duration: "35 min",
        topics: 4,
        progress: 0,
      },
      {
        id: 2,
        title: "Light and Shadow",
        description: "Properties of light",
        difficulty: "Beginner",
        duration: "40 min",
        topics: 4,
        progress: 0,
      },
    ],
  },

  "Grade 7": {
    CBSE: [
      {
        id: 1,
        title: "Heat",
        description: "Heat transfer and temperature",
        difficulty: "Beginner",
        duration: "40 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 2,
        title: "Motion and Time",
        description: "Understanding speed and motion",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 3,
        title: "Electric Current and Its Effects",
        description: "Current and circuits",
        difficulty: "Intermediate",
        duration: "42 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 4,
        title: "Light",
        description: "Reflection and refraction",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 5,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Heat and Temperature",
        description: "Thermal energy",
        difficulty: "Beginner",
        duration: "40 min",
        topics: 4,
        progress: 0,
      },
      {
        id: 2,
        title: "Motion",
        description: "Types of motion",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 5,
        progress: 0,
      },
    ],
    WBSE: [
      {
        id: 1,
        title: "Heat and Its Effects",
        description: "Understanding heat",
        difficulty: "Beginner",
        duration: "42 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 2,
        title: "Speed and Motion",
        description: "Calculating speed",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 4,
        progress: 0,
      },
    ],
  },

  "Grade 8": {
    CBSE: [
      {
        id: 1,
        title: "Force and Pressure",
        description: "Understanding force and pressure",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Friction",
        description: "Types and effects of friction",
        difficulty: "Intermediate",
        duration: "40 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 3,
        title: "Sound",
        description: "Production and propagation of sound",
        difficulty: "Intermediate",
        duration: "42 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 4,
        title: "Light",
        description: "Laws of reflection",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Force and Motion",
        description: "Newton's laws basics",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 2,
        title: "Energy",
        description: "Forms of energy",
        difficulty: "Intermediate",
        duration: "42 min",
        topics: 4,
        progress: 0,
      },
    ],
    WBSE: [
      {
        id: 1,
        title: "Force and Motion",
        description: "Dynamics",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Sound",
        description: "Wave properties",
        difficulty: "Intermediate",
        duration: "40 min",
        topics: 4,
        progress: 0,
      },
    ],
  },

  "Grade 9": {
    CBSE: [
      {
        id: 1,
        title: "Motion",
        description: "Kinematics and equations of motion",
        difficulty: "Intermediate",
        duration: "50 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Force and Laws of Motion",
        description: "Newton's laws and applications",
        difficulty: "Intermediate",
        duration: "52 min",
        topics: 7,
        progress: 0,
      },
      {
        id: 3,
        title: "Gravitation",
        description: "Universal law of gravitation",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 4,
        title: "Work and Energy",
        description: "Energy transformation and conservation",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 5,
        title: "Sound",
        description: "Vibrations, frequency, and resonance",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 5,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Measurements and Motion",
        description: "Physical quantities and motion",
        difficulty: "Intermediate",
        duration: "50 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Laws of Motion",
        description: "Force and momentum",
        difficulty: "Advanced",
        duration: "52 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 3,
        title: "Gravitation",
        description: "Gravitational force",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 4,
        title: "Work, Energy and Power",
        description: "Conservation principles",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 7,
        progress: 0,
      },
    ],
    WBSE: [
      {
        id: 1,
        title: "Measurement",
        description: "Units and measurements",
        difficulty: "Beginner",
        duration: "40 min",
        topics: 4,
        progress: 0,
      },
      {
        id: 2,
        title: "Motion and Force",
        description: "Combined study of motion and forces",
        difficulty: "Intermediate",
        duration: "55 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 3,
        title: "Energy and Work",
        description: "Work, energy, and power",
        difficulty: "Intermediate",
        duration: "50 min",
        topics: 6,
        progress: 0,
      },
    ],
    "State Board": [
      {
        id: 1,
        title: "Motion in a Straight Line",
        description: "Linear motion concepts",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 2,
        title: "Force and Momentum",
        description: "Newton's laws",
        difficulty: "Intermediate",
        duration: "50 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 3,
        title: "Gravitation",
        description: "Gravity and weight",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 5,
        progress: 0,
      },
    ],
  },

  "Grade 10": {
    CBSE: [
      {
        id: 1,
        title: "Light - Reflection and Refraction",
        description: "Laws of reflection and refraction",
        difficulty: "Intermediate",
        duration: "55 min",
        topics: 7,
        progress: 0,
      },
      {
        id: 2,
        title: "Human Eye and Colourful World",
        description: "Eye structure and color dispersion",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 3,
        title: "Electricity",
        description: "Electric current, circuits and Ohm's law",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 4,
        title: "Magnetic Effects of Electric Current",
        description: "Electromagnetic induction",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 7,
        progress: 0,
      },
      {
        id: 5,
        title: "Sources of Energy",
        description: "Renewable and non-renewable energy",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 5,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Force",
        description: "Types of forces",
        difficulty: "Intermediate",
        duration: "50 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Light",
        description: "Reflection, refraction and lenses",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 3,
        title: "Current Electricity",
        description: "Electrical circuits",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 4,
        title: "Magnetism",
        description: "Magnetic fields",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 7,
        progress: 0,
      },
    ],
    WBSE: [
      {
        id: 1,
        title: "Reflection and Refraction of Light",
        description: "Optics fundamentals",
        difficulty: "Intermediate",
        duration: "52 min",
        topics: 7,
        progress: 0,
      },
      {
        id: 2,
        title: "Current Electricity",
        description: "Electric circuits and power",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 3,
        title: "Thermal Phenomena",
        description: "Heat transfer",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
    ],
    "State Board": [
      {
        id: 1,
        title: "Optics",
        description: "Light and vision",
        difficulty: "Intermediate",
        duration: "50 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 2,
        title: "Electricity",
        description: "Current and resistance",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 3,
        title: "Electromagnetism",
        description: "Magnetic effects",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 7,
        progress: 0,
      },
    ],
  },

  "Grade 11": {
    CBSE: [
      {
        id: 1,
        title: "Physical World",
        description: "Nature of physical laws",
        difficulty: "Beginner",
        duration: "35 min",
        topics: 4,
        progress: 0,
      },
      {
        id: 2,
        title: "Units and Measurements",
        description: "SI units and dimensions",
        difficulty: "Intermediate",
        duration: "48 min",
        topics: 6,
        progress: 0,
      },
      {
        id: 3,
        title: "Motion in a Straight Line",
        description: "Kinematics in one dimension",
        difficulty: "Intermediate",
        duration: "52 min",
        topics: 7,
        progress: 0,
      },
      {
        id: 4,
        title: "Laws of Motion",
        description: "Newton's laws applications",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 5,
        title: "Work, Energy and Power",
        description: "Conservative forces",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 7,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Measurements",
        description: "Accuracy and precision",
        difficulty: "Intermediate",
        duration: "45 min",
        topics: 5,
        progress: 0,
      },
      {
        id: 2,
        title: "Kinematics",
        description: "Motion analysis",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 7,
        progress: 0,
      },
      {
        id: 3,
        title: "Dynamics",
        description: "Force and motion",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 8,
        progress: 0,
      },
    ],
  },

  "Grade 12": {
    CBSE: [
      {
        id: 1,
        title: "Electric Charges and Fields",
        description: "Electrostatics",
        difficulty: "Advanced",
        duration: "65 min",
        topics: 9,
        progress: 0,
      },
      {
        id: 2,
        title: "Current Electricity",
        description: "Kirchhoff's laws",
        difficulty: "Advanced",
        duration: "62 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 3,
        title: "Electromagnetic Induction",
        description: "Faraday's law",
        difficulty: "Advanced",
        duration: "60 min",
        topics: 8,
        progress: 0,
      },
      {
        id: 4,
        title: "Wave Optics",
        description: "Interference and diffraction",
        difficulty: "Advanced",
        duration: "58 min",
        topics: 7,
        progress: 0,
      },
    ],
    ICSE: [
      {
        id: 1,
        title: "Electrostatics",
        description: "Electric field and potential",
        difficulty: "Advanced",
        duration: "65 min",
        topics: 9,
        progress: 0,
      },
      {
        id: 2,
        title: "Electromagnetic Waves",
        description: "EM spectrum",
        difficulty: "Advanced",
        duration: "55 min",
        topics: 7,
        progress: 0,
      },
    ],
  },
};